### ISSUE TITLE
Create labels page

### ISSUE THREAD

**Issue by pepelondono** [ezl/lost-item#89]
People want to print labels to have their URL stuck to their items they don't want to lose. Though we are not yet in the capacity of providing them, we have found Mabel Labels stickers pretty useful for this, so we want to show our users how things look with the labels on and where to buy them. 

---
CHANGES NEEDED

(A) Create /labels page according to the wireframes

RESOURCES
1. Wireframes
[wireframe_buy_label.pdf](https://github.com/ezl/lost-item/files/5518113/wireframe_buy_label.pdf)

2. Mabels' logo
[Mabels.zip](https://github.com/ezl/lost-item/files/5517873/Mabels.zip)

3. Mockups of products with the labels
[mockups.zip](https://github.com/ezl/lost-item/files/5518035/mockups.zip)

**Comment by ezl** [comment]
Hi @Emad-salah I did already merge this, but upon testing it on the live site:

1. only 2 out of 3 images are showing up (not seeing the phone one)
2. the suitcase one seems to not fit very well

<img width="1164" alt="image" src="https://user-images.githubusercontent.com/157627/108157692-f6101d80-70a8-11eb-8b7b-2cb933e39ac5.png">

I tested this on the live site which I deployed here: https://www.lost-item.com/labels

Can you please
(A) confirm if you see the same thing
(B) fix if you do, screen shot what you see on the live site if you see something different

**Comment by Emad-salah** [comment]
Hey @ezl, The image was visible for me on local but not on the live site, turned out to be because I'm on a Windows machine, and it's not case-sensitive so it didn't care about the capitalized letter in that iPhone image but the server and your machine are probably Mac/Linux so they couldn't ignore the capitalization.

I have pushed a fix for those 2 issues, Let me know if anything else not working correctly :)
